### PR TITLE
feat: add option for path array exports

### PR DESCRIPTION
**Pull request by souporserious**
Forks `extract-svg-path` locally to add support for exporting arrays in the paths build. It only enables this for `services` and `ui-kit` as these are the only apps that utilize this feature right now.

### CODE REVIEW

**Comment by chantastic** [comment]
this looks like a good implementation of the path arrays idea

i think there needs to be a clear separation between static icons and interactive icons — at a collection level. the recommended cross-framework implementation is svg-sprites — where these would render as stacked paths.

i think isolating an `interactive` on `stateful` collection could be a clear enough boundary to provide a predictable DX

**Comment by chantastic** [comment]
@tage @souporserious 

as a follow-up to standup discussion.

this change does quietly change all all `path` exports for iconsets that aren't in the `experimentalApps`.
instead of being a path merge (which assisted in cases where someone forget to flatten set of paths), it now only returns the first path.

while i do believe interactive icons *should* be a dedicated set, here is an alternative for expediency:

* [ ] add a condition to `writeSVGPathStringsForCollection` that does the collection check
  * [ ] if multi-path icon set, use the array build
  * [ ] else, use the `extract-svg-path` lib currently used
* [ ] remove multi-path icon sets [`services` and `ui-kit`] from sprites build and documentation to avoid confusion

**Comment by souporserious** [comment]
@chantastic this currently works the same way as before for non UI Kit and Services icon builds, the path is still merged if it finds multiples. As of right now on main those interactive icons (checkbox, radio, volume) aren't built either so I think this checks all of those boxes and is good to ship?

**Comment by souporserious** [comment]
Here's the diff for those curious. This is running the build off of `main` staging those changes and then running the build again off of this branch changing only ui-kit paths because it will now have arrays for interactive icons:

image

**Comment by chantastic** [comment]
unfortunately, it does not address the remaining items.
i've opened up #62 to address the requisite changes.

**Comment by souporserious** [comment]
> add a condition to `writeSVGPathStringsForCollection` that does the collection check

Why is this needed?

> if multi-path icon set, use the array build

This is currently the case it only builds multi-path icons for `services` and `ui-kit` sets.

> else, use the `extract-svg-path` lib currently used

This is currently the case as well as it's using the same code from the `extract-svg-path` library.

> remove multi-path icon sets [`services` and `ui-kit`] from sprites build and documentation to avoid confusion

This removes them entirely from sprites, which means they will only be accessible via the paths option. Leaving this as-is means it works exactly as before and doesn't change the way sprites are currently working.

**Pull request merged**
