### PR TITLE
fix(Compound Paths): check-ins, people, giving, groups - mark 2.0

### PR DESCRIPTION
**Pull request by WillDosSantos**
- Fixed
- `Check-ins => x`
- `Check-ins => check`
- `Groups => cards`
- `Giving => download`
- `Giving => page-right-double`
- `People => bars`
- `People => form-paragraph`
- `People => step-back`
- `People => skip-step`

### CODE REVIEW

**Review by dsecrest — COMMENTED** [review]
This looks better, but I'm concerned about the `title` being removed. Maybe we need to take a look at the build process.

**Comment by dsecrest** [comment]
@chantastic Do you have thoughts on this? Specifically, the removal of the `title`s from the svgs.

**Comment by chantastic** [comment]
it's really odd that this is removing `title` ONLY for the icons that changed. investigating

**Comment by chantastic** [comment]
After looking into this, I think the approach for this might need to change.

The null paths in the `paths` files is not a perfect indicator of whether on not an icon has compound paths.
A more reliable indicator of this the layers panel in the source `.ai` file:

image

In the image above, you can see that that there are many more icons with paths that should be combined.

Because this this is such a large change, I would remove all icons from the existing `svg/{collection}/` directories and re-export everything.

That brings me to export.
It appears that the latest Adobe Illustrator doesn't include the `title` attribute by default.

This is an interesting problem.
We don't need them for the sprites.
When using the `<use>` tag, you need to put the title on the containing `<svg>` anyway.
It also doesn't impact any consumers using the `paths/` because they are also constructing their own `<svg>` wrapper (where the title should reside).

I suspect that this only impacts accessibility where folks are using the `svg/` files directly.
And I can't speak to how many instances that is.

However, it's something we might need to provide some guidance on.

As it pertains to this branch...

You can continue making compound paths in the `.ai` source files (as described above) independent of the other issues.

**Pull request closed without merging**
