### PR TITLE
add Figma script

### PR DESCRIPTION
**Pull request by souporserious**
Adds a Node script using the [figma-tools](https://github.com/souporserious/figma-tools) library to make extracting assets from Figma easier. It does not change the build, which still works the same as before. In addition to building the icon set as normal, we can now run the following command to fetch SVGS from [this Figma file](https://www.figma.com/file/jkzIOE4y4uwlpUZZc6z4Nz/Planning-Center-Icons?node-id=1%3A2):

```bash
npm run figma
```

Please note you will need a [personal access token](https://www.figma.com/developers/docs#auth-dev-token) in a .env file at the root of the project in order to fetch the images properly:

```bash
FIGMA_TOKEN="your-token-here"
```

### CODE REVIEW

**Comment by chantastic** [comment]
Does this need a review?
@dsecrest it looks like you requested one from but it is Draft. So I assumed it was just queued up for a future conversation.
As described pre-task, our first goal is to build everything from the a local, version-controlled and stabilizing the apps (and tests) around that before introducing a Figma cloud dependency

**Comment by dsecrest** [comment]
> Does this need a review?
> @dsecrest it looks like you requested one from but it is Draft. So I assumed it was just queued up for a future conversation.
> As described pre-task, our first goal is to build everything from the a local, version-controlled and stabilizing the apps (and tests) around that before introducing a Figma cloud dependency

Sorry about that. I didn't even notice that it was a draft. It's not ready for review then, but I wanted to make sure that we followed up on this before it gets merged, because of the dependency.

**Comment by souporserious** [comment]
@dsecrest this just needs documentation and it should be ready for review. I'll get with @jonsuh to see where it's at since we started working on that on Friday.

@chantastic not sure if you read the summary from Friday, but we were able to build everything directly from Figma. This is just an enhancement and makes it easier to sync things up using the API. Figma keeps everything version controlled by the way, so I don't think we'll need to keep a local Figma file in Github.

**Comment by chantastic** [comment]
yup, read it. i had assumed that there would be another PR that more clearly aligned with the objectives Dustin and I had stated at the onset. the figma file looks promising. we can all work on the staged migration to figma together this week.

**Pull request closed without merging**
